framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_cache: true
    http_method_override: false

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    esi: true
    fragments: true

    php_errors:
        log: true

    http_client:
        scoped_clients:
            budget_insight.client:
                base_uri: 'https://pentiminax-sandbox.biapi.pro/2.0'
            divvydiary.client:
                base_uri: 'https://api.divvydiary.com'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
