version: '3'

services:
  caddy:
    environment:
      - SERVER_NAME=${SERVER_NAME}
    image: caddy:latest
    networks:
      - dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www/synancial
      - caddy_data:/data
      - caddy_config:/config

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: synancial
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    networks:
      - dev
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:20
    volumes:
      - .:/var/www/synancial
    working_dir: /var/www/synancial

  php:
    build: .
    networks:
      - dev
    volumes:
      - ./:/var/www/synancial

networks:
  dev:

volumes:
  caddy_data:
  caddy_config:
  db_data:
