parameters:
  base_url: '%env(BASE_URL)%'
  client_id: '%env(CLIENT_ID)%'
  client_secret: '%env(CLIENT_SECRET)%'
  default_currency_code: '%env(DEFAULT_CURRENCY_CODE)%'
  redirect_uri: '%env(REDIRECT_URI)%'

services:
  _defaults:
    autowire: true.
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\EventSubscriber\LocaleSubscriber:
    arguments: [ '%kernel.default_locale%' ]

  App\EventListener\RequestListener:
    arguments:
      [ '@translation.locale_switcher', '@security.helper' ]
    tags:
      - { name: kernel.event_listener, event: kernel.request }